project_id = "wadvyhwbdukdichmkidk"

[functions.arsenal-live]
verify_jwt = false

[functions.fetch-arsenal-fixtures]
verify_jwt = false

[functions.pump-fun-proxy]
verify_jwt = false

[functions.all-matches]
verify_jwt = false

[functions.save-recording]
verify_jwt = false
